# Generated by Django 5.2 on 2025-04-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chekigari', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
