# Generated by Django 5.2 on 2025-04-16 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chekigari', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='body_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_registration_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('manufacturer_year', models.IntegerField(max_length=4)),
                ('engine_capacity', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')])),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')])),
                ('passanger_capacity', models.IntegerField()),
                ('number_of_doors', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('body_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chekigari.body_type')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chekigari.make')),
            ],
        ),
    ]
