# Generated by Django 5.2 on 2025-04-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chekigari', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vehicle_registration_details',
            new_name='Vehicle_registration_detail',
        ),
    ]
