# Generated by Django 5.2 on 2025-04-16 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chekigari', '0004_rename_vehicle_registration_details_vehicle_registration_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollisionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DamageSeverity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='body_type',
            options={'verbose_name': 'body_type', 'verbose_name_plural': 'body_types'},
        ),
        migrations.AlterModelOptions(
            name='make',
            options={'verbose_name': 'make', 'verbose_name_plural': 'makes'},
        ),
        migrations.AlterModelOptions(
            name='vehicle_registration_detail',
            options={'verbose_name': 'vehicle_registration_details', 'verbose_name_plural': 'vehicle_registration_details'},
        ),
        migrations.AlterField(
            model_name='vehicle_registration_detail',
            name='engine_capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle_registration_detail',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle_registration_detail',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chekigari.make'),
        ),
        migrations.AlterField(
            model_name='vehicle_registration_detail',
            name='manufacturer_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle_registration_detail',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=100),
        ),
        migrations.CreateModel(
            name='accident_report',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accident_date', models.DateTimeField(auto_now_add=True)),
                ('accident_location', models.CharField(max_length=100)),
                ('accident_description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('vehicle_registration_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chekigari.vehicle_registration_detail')),
                ('collision_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chekigari.collisiontype')),
                ('damage_severity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chekigari.damageseverity')),
            ],
        ),
    ]
