# Generated by Django 5.2 on 2025-04-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chekigari', '0005_collisiontype_damageseverity_alter_body_type_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body_type',
            options={'verbose_name': 'Body_type', 'verbose_name_plural': 'Body Types'},
        ),
        migrations.AlterModelOptions(
            name='damageseverity',
            options={'verbose_name': 'Damage_severity', 'verbose_name_plural': 'Damage Severities'},
        ),
        migrations.AlterModelOptions(
            name='make',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vehicle_registration_detail',
            options={'verbose_name': 'Vehicle_registration_details', 'verbose_name_plural': 'Vehicle Registration Details'},
        ),
    ]
