# Generated by Django 5.2 on 2025-04-16 13:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chekigari', '0008_remove_accidentreport_report_id_accidentreport_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle_registration_detail',
            options={'verbose_name': 'Vehicle_registration_detail', 'verbose_name_plural': 'Vehicle Registration Details'},
        ),
        migrations.RemoveField(
            model_name='accidentreport',
            name='id',
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='report_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
